TOCK_USERLAND_BASE_DIR ?= ..

$(TOCK_USERLAND_BASE_DIR)/lua53/lua/lua.h:
	git submodule init $(TOCK_USERLAND_BASE_DIR)/lua53/lua
	git submodule update $(TOCK_USERLAND_BASE_DIR)/lua53/lua

all: | $(TOCK_USERLAND_BASE_DIR)/lua53/lua/lua.h
