# Makefile for user application

# Specify this directory relative to the current application.
TOCK_USERLAND_BASE_DIR = ../../../..

# Which files to compile.
C_SRCS := $(wildcard *.c)

# Include app loading support rules. Rules to generate app binary images.
include $(TOCK_USERLAND_BASE_DIR)/AppMakefile.mk
