.PHONY: clean

TOCK_USERLAND_BASE_DIR ?= ../..

TCPLP_DIR:=$(TOCK_USERLAND_BASE_DIR)/libopenthread/libtcplp

clean:: 
	rm -rf build

all: $(TOCK_USERLAND_BASE_DIR)/libopenthread/openthread/README.md

# confirm openthread git submodule is checked out.
$(TOCK_USERLAND_BASE_DIR)/libopenthread/openthread/README.md:
	git submodule update --init -- $(TOCK_USERLAND_BASE_DIR)/libopenthread/openthread
