.PHONY: clean

LIB_DIR=lib

all:
	echo AVA!!!
	./create_ot-tock

clean:
	rm -rf build
	rm -rf $(LIB_DIR)/libmbedcrypto/build
	rm -rf $(LIB_DIR)/libmbedtls/build
	rm -rf $(LIB_DIR)/libmbedx509/build
	rm -rf $(LIB_DIR)/libopenthread/build
	rm -rf $(LIB_DIR)/libtcplp/build
